### ISSUE TITLE
Extention Requirements

### ISSUE THREAD

**Issue by FeelsBadMan1** [phpBB-Studio/DiceRolls#7]
**Describe the bug**
The selected extension cannot be enabled, please verify the extension’s requirements.

**To Reproduce**
1. Go to the extention enable & disable tab
2. Click on enable extention
3. See error on full screen

**Expected behavior**
I expected that the Extention is working like it should be.

**Screenshots**
![image](https://user-images.githubusercontent.com/40109798/125406918-a7498400-e3b9-11eb-89ff-3951b0e20be3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 - Version 77.0.4054.203

**Smartphone (please complete the following information):**
None

**Additional context**
Im not sure, wich requirement the Extention need and where i find the Requirements.

**Comment by 3D-I** [comment]
https://phpbbstudio.com/viewtopic.php?f=22&t=164

**Comment by FeelsBadMan1** [comment]
thank u that worked. however on the Website i dont see the Dice....

**Comment by 3D-I** [comment]
Please refer to our site for assistance. This is a bug tracker thx.
